# Generated by Django 3.0.5 on 2021-01-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_autor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor_name',
            new_name='author_name',
        ),
    ]
