# Generated by Django 3.1.5 on 2021-01-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210123_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbookrelation',
            options={'verbose_name': 'Лайки, закладки, рейтинг', 'verbose_name_plural': 'Лайки, закладки, рейтинг'},
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
