# Generated by Django 3.1.7 on 2021-04-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210424_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False, verbose_name='В закладках'),
        ),
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True, verbose_name='Рейтинг'),
        ),
    ]
